#!/usr/bin/env sh
# Temporary bypass for deployment
[ "$CI" = "true" ] && exit 0
[ -f "$GIT_DIR/../.husky/_/husky.sh" ] && . "$GIT_DIR/../.husky/_/husky.sh"

# Run formatting on all workspaces
pnpm format:fix
